name: Send weekly email (Brevo)

on:
  schedule:
    # Wednesdays at 02:00 UTC (after your nightly cap update runs)
    - cron: '0 2 * * 3'
  workflow_dispatch:

jobs:
  email:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to commit the chart PNG to Pages
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests matplotlib numpy

      # 1) Generate the chart PNG (and commit it if changed)
      - name: Generate weekly chart
        env:
          SITE_URL: ${{ secrets.SITE_URL }}          # e.g. https://<user>.github.io/<repo>
        run: python scripts/email_report.py --make-chart-only

      # email sending needs API key and recipients
      - name: Send weekly report via Brevo
        env:
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          REPORT_FROM_EMAIL: ${{ secrets.REPORT_FROM_EMAIL }}
          REPORT_TO_EMAILS: ${{ secrets.REPORT_TO_EMAILS }}   # comma/newline separated list
          # fallback single recipient if you prefer:
          REPORT_TO_EMAIL: ${{ secrets.REPORT_TO_EMAIL }}
          SITE_URL: ${{ secrets.SITE_URL }}
        run: python scripts/email_report.py --send-email
